theme: jekyll-theme-so-simple
skin: "/assets/css/skins/naplesnds.css"
locale: en
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200

title: "NDS Naples"
description: "We scugnizzi, and our enjoyment of the Nintendo handheld."
baseurl: "/naplesnds"
url: "https://gamingshitposting.github.io"
logo: "https://i.pinimg.com/originals/d0/bb/47/d0bb4753d0b88fa1e45b1d46a6f9a2bf.jpg"

mathjax:
  enable: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

liquid:
  error_mode: strict
markdown: kramdown
feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss
  - title: Telegram CMgnoranza (Channel)
    url: https://t.me/cmgnoranza
    icon: fab fa-telegram
  - title: Telegram Gaming Shitposting (Group)
    url: https://t.me/gamingshitpost
    icon: fab fa-telegram
  - title: GitHub
    url: https://github.com/GamingShitposting
    icon: fab fa-github
