theme: jekyll-theme-so-simple
skin: "/assets/css/skins/default.css"
locale: en-US
title: "So Simple Development Site"
description: "A simple Jekyll theme for words and pictures."
baseurl: "/naplesnds"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: "/images/so-simple-site-logo.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax:
  enable: true
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

google_analytics:
disqus:
  shortname:
twitter:
  username:

liquid:
  error_mode: strict
markdown: kramdown
feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/
search_full_content: true
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

author:
  name: Michael Rose
  picture: /images/michael-rose-photo.jpg
  email:
  twitter: mmistakes
  links:
    - title: Twitter
      url: https://twitter.com/mmistakes
      icon: fab fa-twitter-square
    - title: Instagram
      url: https://instagram.com/mmistakes
      icon: fab fa-instagram
    - title: GitHub
      url: https://github.com/mmistakes
      icon: fab fa-github-square

footer_links:
  - title: Twitter
    url: https://twitter.com/mmistakes
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/mmistakes
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/mmistakes
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
